### ISSUE TITLE
bug sir

### ISSUE THREAD

**Issue by kingvavasav** [GravelFire/HorizonLaunch_bot#4]
C:\Users\dani\Downloads\HorizonLaunch_bot-main\HorizonLaunch_bot-main>main.py
Traceback (most recent call last):
  File "C:\Users\dani\Downloads\HorizonLaunch_bot-main\HorizonLaunch_bot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\dani\Downloads\HorizonLaunch_bot-main\HorizonLaunch_bot-main\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\dani\Downloads\HorizonLaunch_bot-main\HorizonLaunch_bot-main\bot\utils\launcher.py", line 10, in <module>
    from bot.config import settings
  File "C:\Users\dani\Downloads\HorizonLaunch_bot-main\HorizonLaunch_bot-main\bot\config\__init__.py", line 1, in <module>
    from .config import settings
  File "C:\Users\dani\Downloads\HorizonLaunch_bot-main\HorizonLaunch_bot-main\bot\config\config.py", line 18, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pydantic_settings\main.py", line 84, in __init__
    super().__init__(
  File "C:\Program Files\Python311\Lib\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
RANDOM_DELAY_IN_RUN
  Input should be a valid list [type=list_type, input_value=1, input_type=int]
    For further information visit https://errors.pydantic.dev/2.6/v/list_type

C:\Users\dani\Downloads\HorizonLaunch_bot-main\HorizonLaunch_bot-main>

**Comment by Wickedgent** [comment]
same error
